Repository algorand/conduit, pull requests merged in 2023-07, with the labels that each got.

#122 algod importer: Update sync on WaitForBlock error.
  conduit/plugins/importers/algod/algod_importer.go
  conduit/plugins/importers/algod/algod_importer_test.go
  conduit/plugins/importers/algod/mock_algod_test.go
Labels: Team Lamprey, Bug-Fix

#119 bugfix: postgresql exporter delete task
  conduit/data/config.go
  conduit/pipeline/pipeline.go
  conduit/pipeline/pipeline_test.go
  conduit/plugins/config.go
  conduit/plugins/exporters/postgresql/postgresql_exporter.go
  conduit/plugins/exporters/postgresql/util/prune.go
  conduit/telemetry/telemetry.go
  conduit/telemetry/telemetryCommon.go
  e2e_tests/pyproject.toml
  e2e_tests/src/e2e_common/indexer_db.py
  e2e_tests/src/e2e_conduit/e2econduit.py
  e2e_tests/src/e2e_conduit/fixtures/exporters/postgresql.py
  e2e_tests/src/e2e_conduit/fixtures/importers/follower_algod.py
  e2e_tests/src/e2e_conduit/runner.py
  e2e_tests/src/e2e_conduit/scenarios/__init__.py
  e2e_tests/src/e2e_conduit/scenarios/follower_indexer_scenario.py
  e2e_tests/src/e2e_conduit/subslurp.py
  go.mod
  go.sum
  pkg/cli/internal/initialize/init.go
Labels: Bug-Fix

#124 Fix IndexerWriter.md links.
  docs/tutorials/IndexerWriter.md
Labels: Team Lamprey

#126 Remove the docs-pr release process.
  .github/workflows/docs-pr.yml
  .github/workflows/goreleaser.yml
Labels: Team Lamprey

#127 docs: Update postgres data pruning documentation.
  conduit/plugins/exporters/postgresql/README.md
  conduit/plugins/exporters/postgresql/sample.yaml
Labels: Team Lamprey
