Repository algorand/conduit, pull requests merged in 2023-03, with the labels that each got.

#6 errors(postgresql): Clarify missing ledger state delta message.
  conduit/plugins/exporters/postgresql/postgresql_exporter.go
  conduit/plugins/exporters/postgresql/postgresql_exporter_test.go
Labels: Team Lamprey

#5 filter plugin: include all transaction in group
  conduit/plugins/processors/filterprocessor/config.go
  conduit/plugins/processors/filterprocessor/fields/filter.go
  conduit/plugins/processors/filterprocessor/filter_processor.go
  conduit/plugins/processors/filterprocessor/filter_processor_bench_test.go
  conduit/plugins/processors/filterprocessor/filter_processor_test.go
  conduit/plugins/processors/filterprocessor/sample.yaml
  conduit/plugins/processors/filterprocessor/sample_test.go
Labels: enhancement, Team Lamprey

#8 logging(algod importer): better error messages for GetBlock.
  conduit/plugins/importers/algod/algod_importer.go
  conduit/plugins/importers/algod/algod_importer_test.go
  conduit/plugins/importers/algod/mock_algod_test.go
  conduit/plugins/importers/filereader/filereader_test.go
Labels: Team Lamprey

#10 conduit-docs: conduit_processors_filter_tags.md
  conduit/plugins/processors/filterprocessor/fields/searcher.go
  conduit/plugins/processors/filterprocessor/gen/generate.go
Labels: Team Lamprey

#16 postgres exporter: Add export stat log message matching the old log m…
  conduit/pipeline/pipeline.go
Labels: Team Lamprey

#20 usability: Better error messages and documentation.
  cmd/conduit/internal/list/list.go
  cmd/conduit/main.go
  cmd/conduit/main_test.go
  conduit/config.go
  conduit/pipeline/pipeline.go
  conduit/pipeline/pipeline_test.go
Labels: Team Lamprey

#23 chore: Update gitignore and remove accidental file.
  .gitignore
  cmd/conduit/data/conduit.yml
Labels: Team Lamprey

#22 docs: Add Known Issues section to README.
  README.md
Labels: Team Lamprey

#24 chore: Add license.
  LICENSE
Labels: Team Lamprey

#31 docs: Update inline sample config documentation.
  cmd/conduit/internal/initialize/conduit.yml.example
  conduit/plugins/exporters/filewriter/sample.yaml
  conduit/plugins/exporters/postgresql/sample.yaml
  conduit/plugins/importers/algod/sample.yaml
  conduit/plugins/importers/filereader/sample.yaml
  conduit/plugins/processors/filterprocessor/sample.yaml
Labels: Team Lamprey

#34 docs: Update 'conduit init' CLI help.
  cmd/conduit/internal/initialize/init.go
Labels: Team Lamprey

#35 docs: automation to publish documentation after a release.
  .github/workflows/docs-pr.yml
  .github/workflows/goreleaser.yml
  docs/.pages
  docs/GettingStarted.md
  docs/plugins/home.md
  docs/tutorials/WritingBlocksToFile.md
Labels: Team Lamprey

#42 docs: link to godoc for plugin development and clarify top-level filter plugin behavior.
  conduit/plugins/exporters/README.md
  docs/Development.md
  docs/tutorials/FilterDeepDive.md
Labels: Team Lamprey

#32 algod importer: Add catchup functionality to algod importer
  cmd/conduit/internal/list/list.go
  conduit/data/block_export_data.go
  conduit/init_provider.go
  conduit/metadata.go
  conduit/pipeline/metadata.go
  conduit/pipeline/metadata_test.go
  conduit/pipeline/pipeline.go
  conduit/pipeline/pipeline_test.go
  conduit/plugins/exporters/example/example_exporter.go
  conduit/plugins/exporters/exporter.go
  conduit/plugins/exporters/exporter_factory_test.go
  conduit/plugins/exporters/filewriter/file_exporter.go
  conduit/plugins/exporters/filewriter/file_exporter_test.go
  conduit/plugins/exporters/noop/noop_exporter.go
  conduit/plugins/exporters/noop/noop_exporter_test.go
  conduit/plugins/exporters/postgresql/postgresql_exporter.go
  conduit/plugins/exporters/postgresql/postgresql_exporter_test.go
  conduit/plugins/importers/algod/algod_importer.go
  conduit/plugins/importers/algod/algod_importer_config.go
  conduit/plugins/importers/algod/algod_importer_test.go
  conduit/plugins/importers/algod/mock_algod_test.go
  conduit/plugins/importers/algod/sample.yaml
  conduit/plugins/importers/filereader/filereader.go
  conduit/plugins/importers/filereader/filereader_test.go
  conduit/plugins/importers/importer.go
  conduit/plugins/metadata.go
  conduit/plugins/processors/filterprocessor/filter_processor.go
  conduit/plugins/processors/noop/noop_processor.go
  conduit/plugins/processors/processor.go
  conduit/plugins/processors/processor_factory_test.go
  conduit/plugins/tools/testutil/mockinit.go
  docs/plugins/algod.md
  go.mod
  go.sum
Labels: enhancement
